### PR TITLE
Update ruby version

### PR DESCRIPTION
**Pull request by andriusm**
Updating ruby version as part of the effort to later update to Ruby3, also Ruby 2.6 is no longer installed on servers (https://github.com/vinted/chef/pull/14684)

@dainiusjocas @vinted/platform-backend

### CODE REVIEW

**Review by tomasv — APPROVED** [review]
Is this even used?

**Comment by andriusm** [comment]
Good question, I actually thought that last feature update was a month ago, but actually, it's been 2 years. It's the last mention of ruby 2.6 in our repos. If it's not used, I would like to ask the owners to archive this repo.

/cc @dainiusjocas

**Comment by dainiusjocas** [comment]
> Good question, I actually thought that last feature update was a month ago, but actually, it's been 2 years. It's the last mention of ruby 2.6 in our repos. If it's not used, I would like to ask the owners to archive this repo.
> 
> /cc @dainiusjocas

Not used anymore. Can be removed altogether. @ernestas-poskus any concerns?

**Comment by ernestas-vinted** [comment]
It is still used in Chef https://github.com/vinted/chef/search?q=fluent-plugin-esslowquery we (Boost) don't use slow queries anymore cc @simonasr maybe we can delete blocks from Chef?

**Comment by andriusm** [comment]
I also found this gem https://github.com/vinted/proxysqlweightlifter which wasn't updated for a long time. Perhaps it's also unused and could be archived?

**Comment by ernestas-vinted** [comment]
afaik, ProxySQLweightlifter is used as well cc @DeathBorn 
https://github.com/vinted/chef/search?q=proxysqlweightlifter

**Comment by andriusm** [comment]
Any news?

@ernestas-vinted @simonasr @DeathBorn

**Pull request closed without merging**
