### PR TITLE
Fix plugin regexp and fields for new elastic logs

### PR DESCRIPTION
**Pull request by mazeika**
@vinted/sre 

Tested in production.

### CODE REVIEW

**Comment by vdnt** [comment]
🆗

**Comment by tomas-didziokas** [comment]
🆗

**Comment by benner** [comment]
Version?

**Comment by mazeika** [comment]
@benner entered in [Changelog](https://github.com/vinted/fluent-plugin-esslowquery/blob/master/CHANGELOG.md).

**Pull request merged**
